services:

  core.manager:
      class: CoreBundle\Utils\CoreManager
      arguments: ['@doctrine.orm.default_entity_manager']

  core.makrdownlistener:
    class: ContentBundle\EventListener\MarkdownListener
    arguments: ['@service_container']
    tags:
        -  { name: doctrine.event_listener, event: preUpdate }
        -  { name: doctrine.event_listener, event: prePersist }

#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
