imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: swiftmailer.yml }
    - { resource: framework.yml }
    - { resource: twig.yml }
    - { resource: doctrine.yml }
    - { resource: fos_user.yml }
    - { resource: fos_rest.yml }
    - { resource: fos_oauth.yml }
    - { resource: fos_comment.yml }
    - { resource: "@EntriesBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

nelmio_api_doc: ~