root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /entries/11
        permanent: true


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /dev/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

user:
    resource: Red\UserBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/user

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

entries:
    resource: Red\EntriesBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/entries

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

account_show:
    path:     /entries/{entry}/{slug}
    defaults: { _controller: "EntriesBundle:Default:test", entry: null, slug:null }
    requirements:
      entry: \d+
    methods:  [GET]