NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /dev/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

user:
    resource: Red\UserBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/user

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

entries:
    resource: Red\EntriesBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/entries

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"