root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /entries/11
        permanent: true


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /dev/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

user:
    resource: UserBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/user

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

entries:
    resource: EntriesBundle\Controller\DefaultController
    type:     rest
    prefix:   /api/entries

content:
    resource: ContentBundle\Controller\ContentController
    type:     rest
    prefix:   /api/content

content_related:
    resource: ContentBundle\Controller\ContentRelatedController
    type:     rest
    prefix:   /api/content/related



fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"




entries_entry:
    path:     /entries/{entry}
    defaults: { _controller: "EntriesBundle:Default:getEntry", entry: null, _format:"html"}
    requirements:
      entry: \d+
    methods:  [GET]

channel:
    resource: '@ChannelBundle/Resources/config/routing.yml'
